ScoreMe.UI/Controllers/PackageController.cs
using PagedList;
using ScoreMe.DAL;
using ScoreMe.DAL.DBModel;
using ScoreMe.DAL.DTO;
using ScoreMe.DAL.Objects;
using ScoreMe.DAL.Repositories;
using ScoreMe.UI.Attributes;
using ScoreMe.UI.Enums;
using ScoreMe.UI.Models;
using ScoreMe.UI.Services;
using ScoreMe.UTILITY.Custom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace ScoreMe.UI.Controllers
{
    [LoginCheck]
    [AccessRightsCheck]
    public class PackageController : Controller
    {
        [Description("Paket siyahısı")]
        public ActionResult Index(int? page, string vl, string prm = null)
        {
            PackageRepository repository = new PackageRepository();
            try
            {
                Search search = new Search();

                search = SetValue(page, vl, prm);

                int pageSize = 15;
                int pageNumber = (page ?? 1);

                PackageVM viewModel = new PackageVM();
                viewModel.Search = search;

                viewModel.Search.pageSize = pageSize;
                viewModel.Search.pageNumber = pageNumber;

                viewModel.RPackageList = repository.SW_GetPackages(viewModel.Search);

                viewModel.ListCount = repository.SW_GetPackagesCount(viewModel.Search);
                int[] pc = new int[viewModel.ListCount];

                viewModel.Paging = pc.ToPagedList(pageNumber, pageSize);



                return Request.IsAjaxRequest()
              ? (ActionResult)PartialView("PartialIndex", viewModel)
              : View(viewModel);
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Error", "Error"));
            }
        }
        public Search SetValue(int? page, string vl, string prm = null)
        {
            if (prm == null && page == null)
            {
                Search ss = new Search();
                Session["SearchInfo"] = ss;
            }

            if (!string.IsNullOrEmpty(vl))
            {
                vl = StripTag.strSqlBlocker(vl);
            }

            Search search = new Search();

            search = (Search)Session["SearchInfo"];

            if (prm != null)
            {
                PropertyInfo propertyInfos = search.GetType().GetProperty(prm);
                propertyInfos.SetValue(search, Convert.ChangeType(vl, propertyInfos.PropertyType), null);
            }

            Session["SearchInfo"] = search;

            return search;

        }

        [Description("Yeni paket əlavə etmək")]
        public ActionResult Create()
        {
            PackageVM viewModel = new PackageVM();
            viewModel = poulateDropDownList(viewModel);
            return View(viewModel);

        }
        [HttpPost]
        public ActionResult Create(PackageVM viewModel)
        {

            try
            {
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {
                    if (ModelState.IsValid)
                    {
                        tbl_Package item = new tbl_Package()
                        {
                            Mobile_EVID = viewModel.Mobile_EVID,
                            PackageName = viewModel.PackageName,
                            PackageSize = viewModel.PackageSize,
                            Validity = viewModel.Validity,
                            ValidityDesc = viewModel.ValidityDesc,
                            InsertDate = DateTime.Now,
                            InsertUser = UserProfile.UserId
                        };
                        CRUDOperation dataOperations = new CRUDOperation();
                        tbl_Package dbItem = dataOperations.AddPackage(item);
                        if (dbItem != null)
                        {
                            TempData["success"] = "Ok";
                            TempData["message"] = "Məlumatlar uğurla əlavə olundu";
                            return RedirectToAction("Index");

                        }
                        else
                        {
                            TempData["success"] = "notOk";
                            TempData["message"] = "Məlumatlar əlavə olunarkən xəta baş verdi";
                            return RedirectToAction("Index");

                        }

                    }
                }
                throw new ApplicationException("Invalid model");
            }
            catch (ApplicationException ex)
            {
                viewModel = poulateDropDownList(viewModel);

                return View(viewModel);
            }
           

        }
        [Description("Paket redaktə etmək")]
        public ActionResult Edit(int id)
        {
            PackageVM viewModel = new PackageVM();
            viewModel = poulateDropDownList(viewModel);
            CRUDOperation dataOperations = new CRUDOperation();

            tbl_Package tblItem = dataOperations.GetPackageByID(id);

            viewModel.PackageID = id;
            viewModel.Mobile_EVID = tblItem.Mobile_EVID;
            viewModel.PackageName = tblItem.PackageName;
            viewModel.PackageSize = tblItem.PackageSize;
            viewModel.Validity = tblItem.Validity;
            viewModel.ValidityDesc = tblItem.ValidityDesc;
            return View(viewModel);

        }
        [HttpPost]
        public ActionResult Edit(PackageVM viewModel)
        {
            try
            {
            
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {
                    if (ModelState.IsValid)
                    {
                        tbl_Package item = new tbl_Package()
                        {
                            ID = viewModel.PackageID,
                            Mobile_EVID = viewModel.Mobile_EVID,
                            PackageName = viewModel.PackageName,
                            PackageSize = viewModel.PackageSize,
                            Validity = viewModel.Validity,
                            ValidityDesc=viewModel.ValidityDesc,
                            UpdateDate = DateTime.Now,
                            UpdateUser = UserProfile.UserId

                        };

                        CRUDOperation dataOperations = new CRUDOperation();
                        tbl_Package dbItem = dataOperations.UpdatePackage(item);
                        if (dbItem != null)
                        {
                            TempData["success"] = "Ok";
                            TempData["message"] = "Məlumatlar uğurla dəyişdirildi";
                            return RedirectToAction("Index");

                        }
                        else
                        {
                            TempData["success"] = "notOk";
                            TempData["message"] = "Məlumatlar dəyişdirilərkən xəta baş verdi";
                            return RedirectToAction("Index");

                        }
                    }
                }

                throw new ApplicationException("Invalid model");
            }
            catch (ApplicationException ex)
            {
                viewModel = poulateDropDownList(viewModel);
                return View(viewModel);
            }

        }
        [Description("Paket sil")]
        public ActionResult Delete(int id)
        {
            try
            {
                CRUDOperation dataOperations = new CRUDOperation();
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {
                    dataOperations.DeletePackage(id, UserProfile.UserId);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Error", "Error"));
            }
        }
        private PackageVM poulateDropDownList(PackageVM viewModel)
        {
            viewModel.MobileEVList = EnumService.GetEnumValueListByEcID((int)CategoryEnum.OperatorType);
            return viewModel;
        }


        #region PackagePrice
        public ActionResult PriceIndex(int packageID)
        {
            PackageRepository repository = new PackageRepository();
            List<PackagePriceDTO> packagePrices = repository.GetPackagePricesByPackageID(packageID);
            PackageVM packageVM = new PackageVM();
            packageVM.PackageID = packageID;
            packageVM.RPackagePriceList = packagePrices;
            return View(packageVM);
        }
        public ActionResult CreatePrice(int packageID)
        {
            PackageVM viewModel = new PackageVM();
            viewModel.PackageID = packageID;
            viewModel = populatePriceDropDownList(viewModel);
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult CreatePrice(PackageVM viewModel)
        {
            try
            {
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {

                    tbl_PackagePrice price = new tbl_PackagePrice()
                    {
                        PackageID = viewModel.PackageID,
                        Source_EVID = viewModel.Source_EVID,
                        BeginDate = viewModel.BeginDate,
                        EndDate = viewModel.EndDate,
                        Price = viewModel.Price,
                        Point = viewModel.Point,
                        InsertDate = DateTime.Now,
                        InsertUser = UserProfile.UserId

                    };

                    CRUDOperation operations = new CRUDOperation();

ScoreMe.UI/Views/Package/Create.cshtml
@model ScoreMe.UI.Models.PackageVM
@{
    ViewBag.Title = "Paket əlavə edilməsi ekranı";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Mobile_EVID, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(x => Model.Mobile_EVID, new SelectList(Model.MobileEVList, "Value", "Text"), htmlAttributes: new { @class = "select2 form-control", tabindex = 1 })
                @Html.ValidationMessageFor(model => model.Mobile_EVID, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.PackageName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.PackageName, new { htmlAttributes = new { @class = "form-control", tabindex = 2 } })
                @Html.ValidationMessageFor(model => model.PackageName, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.PackageSize, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.PackageSize, new { htmlAttributes = new { @class = "form-control", tabindex = 3 } })
                @Html.ValidationMessageFor(model => model.PackageSize, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.Validity, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Validity, new { htmlAttributes = new { @class = "form-control", tabindex = 4 } })
                @Html.ValidationMessageFor(model => model.Validity, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.ValidityDesc, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.ValidityDesc, new { htmlAttributes = new { @class = "form-control", tabindex = 5 } })
                @Html.ValidationMessageFor(model => model.ValidityDesc, "", new { @class = "text-danger" })

            </div>

        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-6 control-label">
                @Html.ActionLink("Listə Geri Dön", "Index", "Package", null, new { @class = "btn btn-primary btn-lg btn-block" })
            </div>
            <div class="col-md-6 control-label">
                <input id="frmPosition" type="submit" value="Yarat" class="btn btn-primary btn-lg btn-block" tabindex="9" />
            </div>
        </div>
    </div>
}

ScoreMe.UI/Views/Package/CreatePrice.cshtml
@model ScoreMe.UI.Models.PackageVM
@{
    ViewBag.Title = "Əlaqə vasitəsi əlavə et ekranı";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-4">
                @Html.HiddenFor(model => model.PackageID)
                @Html.LabelFor(model => model.Source_EVID, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(x => Model.Source_EVID, new SelectList(Model.SourceEVList, "Value", "Text"), htmlAttributes: new { @class = "select2 form-control", tabindex = 1 })
                @Html.ValidationMessageFor(model => model.Source_EVID, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">

                @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control", tabindex = 2 } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">

                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", tabindex = 3 } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">

                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", tabindex = 4 } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">

                @Html.LabelFor(model => model.Point, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Point, new { htmlAttributes = new { @class = "form-control", tabindex = 5 } })
                @Html.ValidationMessageFor(model => model.Point, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-6 control-label">
                @Html.ActionLink("Listə Geri Dön", "PriceIndex", "Package", new { packageID = Model.PackageID }, new { @class = "btn btn-primary btn-lg btn-block" })

            </div>
            <div class="col-md-6 control-label">
                <input id="frmEmployee" type="submit" value="Yarat" class="btn btn-primary btn-lg btn-block" tabindex="16" />

            </div>
        </div>
    </div>
}

ScoreMe.UI/Views/Package/Edit.cshtml
@model ScoreMe.UI.Models.PackageVM
@{
    ViewBag.Title = "Paket redakte edilməsi ekranı";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="row">

        <div class="col-md-4">
            @Html.HiddenFor(model => model.PackageID)
            @Html.LabelFor(model => model.Mobile_EVID, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(x => Model.Mobile_EVID, new SelectList(Model.MobileEVList, "Value", "Text"), htmlAttributes: new { @class = "select2 form-control", tabindex = 1 })
            @Html.ValidationMessageFor(model => model.Mobile_EVID, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.PackageName, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.PackageName, new { htmlAttributes = new { @class = "form-control", tabindex = 2 } })
            @Html.ValidationMessageFor(model => model.PackageName, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.PackageSize, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.PackageSize, new { htmlAttributes = new { @class = "form-control", tabindex = 3 } })
            @Html.ValidationMessageFor(model => model.PackageSize, "", new { @class = "text-danger" })

        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Validity, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Validity, new { htmlAttributes = new { @class = "form-control", tabindex = 4 } })
            @Html.ValidationMessageFor(model => model.Validity, "", new { @class = "text-danger" })

        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.ValidityDesc, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.ValidityDesc, new { htmlAttributes = new { @class = "form-control", tabindex = 5 } })
            @Html.ValidationMessageFor(model => model.ValidityDesc, "", new { @class = "text-danger" })

        </div>

    </div>
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-6 control-label">
            @Html.ActionLink("Listə Geri Dön", "Index", "EnumCategory", null, new { @class = "btn btn-primary btn-lg btn-block" })
        </div>
        <div class="col-md-6 control-label">
            <input id="frmPosition" type="submit" value="Dəyiş" class="btn btn-primary btn-lg btn-block" tabindex="9" />
        </div>
    </div>
</div>
}

ScoreMe.UI/Views/Package/EditPrice.cshtml
@model ScoreMe.UI.Models.PackageVM
@{
    ViewBag.Title = "Əlaqə vasitəsi redaktə ekranı";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-4">
                @Html.HiddenFor(model => model.PackagePriceID)
                @Html.HiddenFor(model => model.PackageID)
                @Html.LabelFor(model => model.Source_EVID, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(x => Model.Source_EVID, new SelectList(Model.SourceEVList, "Value", "Text"), htmlAttributes: new { @class = "select2 form-control", tabindex = 1 })
                @Html.ValidationMessageFor(model => model.Source_EVID, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">

                @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control", tabindex = 2 } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">

                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", tabindex = 3 } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">

                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", tabindex = 4 } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">

                @Html.LabelFor(model => model.Point, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Point, new { htmlAttributes = new { @class = "form-control", tabindex = 5 } })
                @Html.ValidationMessageFor(model => model.Point, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-6 control-label">
                @Html.ActionLink("Listə Geri Dön", "PriceIndex", "Package", new { packageID = Model.PackageID }, new { @class = "btn btn-primary btn-lg btn-block" })

            </div>
            <div class="col-md-6 control-label">
                <input id="frmEmployee" type="submit" value="Dəyiş" class="btn btn-primary btn-lg btn-block" tabindex="16" />

            </div>
        </div>
    </div>
}

ScoreMe.UI/Views/Package/Index.cshtml
@model ScoreMe.UI.Models.PackageVM
@{
    ViewBag.Title = "Paket siyahisi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-12">


        <div class="clearfix"></div><br />

        <div class="well bs-component">

            <a class="btn btn-warning pull-right btn-icon" href="@Url.Action("Create","Package")"><span class="fa fa-plus"></span> Əlavə et</a>

            <div class="clearfix"></div>
            <div class="table-responsive">
                <table class="table table-bordered" style="margin:0;">
                    <tbody>
                        <tr>
                            <th class="col-md-2" style="font-size:14px; text-align:center; vertical-align:middle; background-color: gainsboro;">
                                @Html.DisplayNameFor(model => model.Mobile_EVID)
                                <input onkeyup="Search(this, 'Package', 'Index', 'Code')" class="form-control" placeholder="axtar" />
                            </th>
                            <th class="col-md-2" style="font-size:14px; text-align:center; vertical-align:middle; background-color: gainsboro;">
                                @Html.DisplayNameFor(model => model.PackageName)
                                <input onkeyup="Search(this, 'Package', 'Index', 'Name')" class="form-control" placeholder="axtar" />
                            </th>


                            <th class="col-md-2" style="font-size:14px; text-align:center; vertical-align:middle; background-color: gainsboro;">
                                @Html.DisplayNameFor(model => model.PackageSize)
                            </th>
                            <th class="col-md-1" style="font-size:14px; text-align:center; vertical-align:middle; background-color: gainsboro;">
                                @Html.DisplayNameFor(model => model.Validity)
                            </th>
                            <th class="col-md-2" style="font-size:14px; text-align:center; vertical-align:middle; background-color: gainsboro;">
                                @Html.DisplayNameFor(model => model.ValidityDesc)
                            </th>

                            <th class="col-md-2" style="font-size:14px; text-align:center; vertical-align:middle; background-color:gainsboro;">
                                Redaktə et
                                </br>
                                Sil
                            </th>
                        </tr>
                    </tbody>
                </table>
                <div id="AjaxPaginationList">
                    @Html.Partial("PartialIndex")
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/pagedList.js"></script>

ScoreMe.UI/Views/Package/PartialIndex.cshtml
@model ScoreMe.UI.Models.PackageVM
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "";
}




<div class="col-sm-1 col-sm-offset-11" style="position: absolute;">
    <span class="label label-danger pull-right badgemargin">@Model.ListCount</span>
</div>

<table class="table table-bordered">
    <tbody>
        @foreach (var item in Model.RPackageList)
        {
        <tr>
            <td class="col-md-2">
                @Html.DisplayFor(modelItem => item.Mobile_EVDesc)
            </td>
            <td class="col-md-2">
                @Html.DisplayFor(modelItem => item.PackageName)
            </td>

            <td class="col-md-2">
                @Html.DisplayFor(modelItem => item.PackageSize)
            </td>

            <td class="col-md-2">
                @Html.DisplayFor(modelItem => item.Validity)
            </td>
            <td class="col-md-2">
                @Html.DisplayFor(modelItem => item.ValidityDesc)
            </td>

            <td class="col-md-1 shsingle text-center" style="font-size:16px;">
                <a class="btn  btn-primary active btn-xs" title="Redaktə et" href="@Url.Action("Edit","Package", new { id = item.PackageID})"><span class="fa fa-pencil"></span></a>
                <span title="Sil"> @Html.ActionLink(" ", "Delete", "Package", new { id = item.PackageID }, new { @onclick = "return confirm('Silmək istədiyinizə əminsinizmi?.');", @class = "glyphicon glyphicon-trash" })</span>

                <a class="btn btn-primary active btn-xs" data-toggle="tooltip" title="Price list" href="@Url.Action("PriceIndex","Package", new {  packageID= item.PackageID})"><span class="fa fa-th-list"></span></a>
            </td>

        </tr>
        }
    </tbody>
</table>


<div class="box-footer clearfix">
    Səhifə @(Model.Paging.PageCount < Model.Paging.PageNumber ? 0 : Model.Paging.PageNumber) (cəmi @Model.Paging.PageCount)
    @Html.PagedListPager(Model.Paging, page => Url.Action("Index", new { page }))
</div>

ScoreMe.UI/Views/Package/PriceIndex.cshtml
@model ScoreMe.UI.Models.PackageVM
@{
    ViewBag.Title = "Paket qiymətlərinin listəsi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="row">
    <div class="col-md-12">
        <div class="clearfix"></div><br />

        <div class="well bs-component">

            <a class="btn btn-warning active pull-left btn-icon" data-toggle="tooltip" title="geri dön" href="@Url.Action("Index","Package", null)"><span class="fa fa-backward"></span> Geri dön</a>

            <a class="btn btn-warning active pull-right btn-icon" data-toggle="tooltip" title="əlavə et" href="@Url.Action("CreatePrice","Package", new { packageID = Model.PackageID})"><span class="fa fa-plus"></span>Əlavə et </a>



            <div class="clearfix"></div>
            <div class="table-responsive">
                <table class="table table-bordered" style="margin:0;">
                    <tbody>
                        <tr>
                            <th class="col-md-2">
                                @Html.DisplayNameFor(model => model.Source_EVID)
                            </th>
                            <th class="col-md-2">
                                @Html.DisplayNameFor(model => model.BeginDate)
                            </th>
                            <th class="col-md-2">
                                @Html.DisplayNameFor(model => model.EndDate)
                            </th>
                            <th class="col-md-2">
                                @Html.DisplayNameFor(model => model.Price)
                            </th>
                            <th class="col-md-2">
                                @Html.DisplayNameFor(model => model.Point)
                            </th>
                            <th class="col-md-2" style="font-size:16px;">redaktə et | sil | detal əlavə et (məlumat)</th>
                        </tr>

                        @foreach (var item in Model.RPackagePriceList)
                        {
                    <tr>
                        <td class="col-md-2">
                            @Html.DisplayFor(modelItem => item.Source_EVDesc)
                        </td>
                        <td class="col-md-2">
                            @Html.DisplayFor(modelItem => item.BeginDate)
                        </td>
                        <td class="col-md-2">
                            @Html.DisplayFor(modelItem => item.EndDate)
                        </td>
                        <td class="col-md-2">
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td class="col-md-2">
                            @Html.DisplayFor(modelItem => item.Point)
                        </td>
                        <td class="col-md-2 shsingle text-left" style="font-size:16px;">

                            <a class="btn btn-primary active btn-xs" data-toggle="tooltip" title="redaktə et" href="@Url.Action("EditPrice","Package", new { priceID = item.PackagePriceID})"><span class="fa fa-pencil"></span></a>
                            <span title="sil"> @Html.ActionLink(" ", "DeletePrice", "Package", new { priceID = item.PackagePriceID, packageID = item.PackageID }, new { @onclick = "return confirm('Silmək istədiyinizə əminsinizmi');", @class = "glyphicon glyphicon-trash" })</span>

                        </td>

                    </tr>

                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-lg" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" id="modelContent">
        </div>
    </div>
</div>

<script>
    function createModal(url) {
        $('#modelContent').load(url);
        $('#myModal').modal('show');
    }
</script>


<script type="text/javascript">
    $(document).ready(function () {

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

                var deyer = '@TempData["success"]';
                if (deyer== 'Ok')
                {
                    toastr.success('@TempData["message"]');
                }
                else if (deyer == 'notOk')
                {
                    toastr.warning('@TempData["message"]');

                }

    });
</script>

@{
    TempData["success"] = null;
    TempData["message"] = "";
}