ScoreMe.UI/Controllers/AppInformationController.cs
using ScoreMe.DAL;
using ScoreMe.DAL.DBModel;
using ScoreMe.DAL.Objects;
using ScoreMe.UI.Attributes;
using ScoreMe.UI.Enums;
using ScoreMe.UI.Models;
using ScoreMe.UI.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScoreMe.UI.Controllers
{
    [LoginCheck]
    [AccessRightsCheck]
    public class AppInformationController : Controller
    {
        [Description("App məlumatlarının siyahısı")]
        public ActionResult Index()
        {
            CRUDOperation cRUDOperation = new CRUDOperation();
            try
            {
               


                AppInformationVM viewModel = new AppInformationVM();
                viewModel.RAppInformationList = cRUDOperation.GetAppGroupInformations();

               return View(viewModel);
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Error", "Error"));
            }
        }
 
        [Description("Yeni App məlumatını əlavə etmək")]
        public ActionResult Create()
        {
            AppInformationVM viewModel = new AppInformationVM();
           // viewModel = poulateDropDownList(viewModel);
            return View(viewModel);

        }
        [HttpPost]
        public ActionResult Create(AppInformationVM viewModel)
        {

            try
            {
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {
                    if (ModelState.IsValid)
                    {
                        tbl_AppGroupInformation item = new tbl_AppGroupInformation()
                        {
                            CategoryType = viewModel.CategoryType,
                            CategoryName = viewModel.CategoryName,
                            PriceUsage = viewModel.PriceUsage,
                            PointUsage = viewModel.PointUsage,
                            PriceCount = viewModel.PriceCount,
                            PointCount = viewModel.PointCount,
                            InsertDate = DateTime.Now,
                            InsertUser = UserProfile.UserId
                        };
                        CRUDOperation dataOperations = new CRUDOperation();

                        tbl_AppGroupInformation operatorInformationControl = dataOperations.ControlAppGroupInformation(item);
                        if (operatorInformationControl != null)
                        {
                            TempData["success"] = "notOk";
                            TempData["message"] = "Eyni parametrelerə sahib məlumat sistemdə mövcudur";
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            tbl_AppGroupInformation dbItem = dataOperations.UpdateAppGroupInformation(item);
                            if (dbItem != null)
                            {
                                TempData["success"] = "Ok";
                                TempData["message"] = "Məlumatlar uğurla əlavə olundu";
                                return RedirectToAction("Index");

                            }
                            else
                            {
                                TempData["success"] = "notOk";
                                TempData["message"] = "Məlumatlar əlavə olunarkən xəta baş verdi";
                                return RedirectToAction("Index");

                            }

                        }


                    }

                }
                throw new ApplicationException("Invalid model");
            }

            catch (ApplicationException ex)
            {

                return View(viewModel);
            }


        }
        [Description("App məlumatını redaktə etmək")]
        public ActionResult Edit(int id)
        {
            AppInformationVM viewModel = new AppInformationVM();


            CRUDOperation dataOperations = new CRUDOperation();

            tbl_AppGroupInformation tblItem = dataOperations.GetAppGroupInformationById(id);


            viewModel.ID = id;
            viewModel.CategoryType = tblItem.CategoryType;
            viewModel.CategoryName = tblItem.CategoryName;
            viewModel.PriceUsage = tblItem.PriceUsage == null ? 0 : (decimal)tblItem.PriceUsage;
            viewModel.PointUsage = tblItem.PointUsage == null ? 0 : (decimal)tblItem.PointUsage;
            viewModel.PriceCount = tblItem.PriceCount == null ? 0 : (decimal)tblItem.PriceCount;
            viewModel.PointCount = tblItem.PointCount == null ? 0 : (decimal)tblItem.PointCount;

            return View(viewModel);

        }
        [HttpPost]
        public ActionResult Edit(AppInformationVM viewModel)
        {
            try
            {

                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {
                    if (ModelState.IsValid)
                    {
                        tbl_AppGroupInformation item = new tbl_AppGroupInformation()
                        {
                            ID = viewModel.ID,
                            CategoryType = viewModel.CategoryType,
                            CategoryName = viewModel.CategoryName,
                            PriceUsage = viewModel.PriceUsage,
                            PointUsage = viewModel.PointUsage,
                            PriceCount = viewModel.PriceCount,
                            PointCount = viewModel.PointCount,
                            UpdateDate = DateTime.Now,
                            UpdateUser = UserProfile.UserId
                        };

                        CRUDOperation dataOperations = new CRUDOperation();
                        tbl_AppGroupInformation dbItem = dataOperations.UpdateAppGroupInformation(item);
                        if (dbItem != null)
                        {
                            TempData["success"] = "Ok";
                            TempData["message"] = "Məlumatlar uğurla dəyişdirildi";
                            return RedirectToAction("Index");

                        }
                        else
                        {
                            TempData["success"] = "notOk";
                            TempData["message"] = "Məlumatlar dəyişdirilərkən xəta baş verdi";
                            return RedirectToAction("Index");

                        }
                    }
                }

                throw new ApplicationException("Invalid model");
            }
            catch (ApplicationException ex)
            {
                return View(viewModel);
            }

        }
        [Description("App məlumatını sil")]
        public ActionResult Delete(int id)
        {
            try
            {
                CRUDOperation dataOperations = new CRUDOperation();
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {
                    dataOperations.DeleteAppGroupInformation(id, UserProfile.UserId);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Error", "Error"));
            }
        }
 
    }
}

ScoreMe.UI/Views/AppInformation/Edit.cshtml
@model ScoreMe.UI.Models.AppInformationVM
@{
    ViewBag.Title = "Operator məlumatlarının redakte edilməsi ekranı";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="row">
            <div class="col-md-4">
                @Html.HiddenFor(model => model.ID)
                @Html.LabelFor(model => model.CategoryType, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.CategoryType, new { htmlAttributes = new { @class = "form-control", tabindex = 1 } })
                @Html.ValidationMessageFor(model => model.CategoryType, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control", tabindex = 2 } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.PriceUsage, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.PriceUsage, new { htmlAttributes = new { @class = "form-control", tabindex = 5 } })
                @Html.ValidationMessageFor(model => model.PriceUsage, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.PointUsage, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.PointUsage, new { htmlAttributes = new { @class = "form-control", tabindex = 6 } })
                @Html.ValidationMessageFor(model => model.PointUsage, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.PriceCount, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.PriceCount, new { htmlAttributes = new { @class = "form-control", tabindex = 7 } })
                @Html.ValidationMessageFor(model => model.PriceCount, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.PointCount, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.PointCount, new { htmlAttributes = new { @class = "form-control", tabindex = 8 } })
                @Html.ValidationMessageFor(model => model.PointCount, "", new { @class = "text-danger" })

            </div>


        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-6 control-label">
                @Html.ActionLink("Listə Geri Dön", "Index", "AppInformation", null, new { @class = "btn btn-primary btn-lg btn-block" })
            </div>
            <div class="col-md-6 control-label">
                <input id="frmPosition" type="submit" value="Dəyiş" class="btn btn-primary btn-lg btn-block" tabindex="9" />
            </div>
        </div>
    </div>
}

ScoreMe.UI/Views/AppInformation/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model ScoreMe.UI.Models.AppInformationVM


@{


    <div class="row">
        <div class="col-md-12">


            <div class="clearfix"></div><br />

            <div class="well bs-component">
                <a class="btn btn-warning pull-right btn-icon" href="@Url.Action("Create","AppInformation")"><span class="fa fa-plus"></span> Əlavə et</a>

                <div class="clearfix"></div>
                <table id="example" class="table table-striped table-bordered nowrap" style="width:100%">
                    <thead>
                        <tr>
                            <th> @Html.DisplayNameFor(model => model.CategoryType)</th>
                            <th> @Html.DisplayNameFor(model => model.CategoryName)</th>
                            <th> @Html.DisplayNameFor(model => model.PriceUsage)</th>
                            <th> @Html.DisplayNameFor(model => model.PointUsage)</th>
                            <th> @Html.DisplayNameFor(model => model.PriceCount)</th>
                            <th> @Html.DisplayNameFor(model => model.PointCount)</th>
                        </tr>
                    </thead>
                    <tbody>

                        @{
                            var obj = Model.RAppInformationList;
                            if (obj != null)
                            {
                                foreach (var item in Model.RAppInformationList)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CategoryType)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CategoryName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PriceUsage)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.PointUsage)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PriceCount)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PointCount)
                                        </td>

                                    </tr>
                                }
                            }


                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    
}