ScoreMe.UI/Controllers/EnumCategoryController.cs
using PagedList;
using ScoreMe.DAL;
using ScoreMe.DAL.DBModel;
using ScoreMe.DAL.Objects;
using ScoreMe.DAL.Repositories;
using ScoreMe.UI.Attributes;
using ScoreMe.UI.Models;
using ScoreMe.UTILITY.Custom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace ScoreMe.UI.Controllers
{
    [LoginCheck]
    [AccessRightsCheck]
    public class EnumCategoryController : Controller
    {
        // GET: EnumCategory
     
        [Description("Enum Kategori siyahısı")]
        public ActionResult Index(int? page, string vl, string prm = null)
        {
            EnumRepository repository = new EnumRepository();
            try
            {
                Search search = new Search();

                search = SetValue(page, vl, prm);

                int pageSize = 15;
                int pageNumber = (page ?? 1);

                EnumVM viewModel = new EnumVM();
                viewModel.Search = search;

                viewModel.Search.pageSize = pageSize;
                viewModel.Search.pageNumber = pageNumber;

                viewModel.REnumCategoryList = repository.SW_GetEnumCategories(viewModel.Search);

                viewModel.ListCount = repository.SW_GetEnumCategoriesCount(viewModel.Search);
                int[] pc = new int[viewModel.ListCount];

                viewModel.Paging = pc.ToPagedList(pageNumber, pageSize);



                return Request.IsAjaxRequest()
              ? (ActionResult)PartialView("PartialIndex", viewModel)
              : View(viewModel);
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Error", "Error"));
            }
        }
        public Search SetValue(int? page, string vl, string prm = null)
        {
            if (prm == null && page == null)
            {
                Search ss = new Search();
                Session["SearchInfo"] = ss;
            }

            if (!string.IsNullOrEmpty(vl))
            {
                vl = StripTag.strSqlBlocker(vl);
            }

            Search search = new Search();

            search = (Search)Session["SearchInfo"];

            if (prm != null)
            {
                PropertyInfo propertyInfos = search.GetType().GetProperty(prm);
                propertyInfos.SetValue(search, Convert.ChangeType(vl, propertyInfos.PropertyType), null);
            }

            Session["SearchInfo"] = search;

            return search;

        }

        [Description("Yeni enum kategori əlavə etmək")]
        public ActionResult Create()
        {
            EnumVM viewModel = new EnumVM();
            return View(viewModel);

        }
        [HttpPost]
        public ActionResult Create(EnumVM viewModel)
        {

            try
            {
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {

                    tbl_EnumCategory item = new tbl_EnumCategory()
                    {
                        Code = viewModel.EnumCategoryCode,
                        Name = viewModel.EnumCategoryName,
                        Description = viewModel.EnumCategoryDesc,
                        InsertDate = DateTime.Now,
                        InsertUser = UserProfile.UserId

                    };

                    CRUDOperation dataOperations = new CRUDOperation();
                    tbl_EnumCategory dbItem = dataOperations.AddEnumCategory(item);
                    if (dbItem != null)
                    {
                        TempData["success"] = "Ok";
                        TempData["message"] = "Məlumatlar uğurla əlavə olundu";
                        return RedirectToAction("Index");

                    }
                    else
                    {
                        TempData["success"] = "notOk";
                        TempData["message"] = "Məlumatlar əlavə olunarkən xəta baş verdi";
                        return RedirectToAction("Index");

                    }


                }
            }
            catch (ApplicationException ex)
            {


                return View(viewModel);
            }
            throw new ApplicationException("Invalid model");

        }
        [Description("Enum karegoini redaktə etmək")]
        public ActionResult Edit(int id)
        {
            EnumVM viewModel = new EnumVM();
            CRUDOperation dataOperations = new CRUDOperation();

            tbl_EnumCategory tblItem = dataOperations.GetEnumCategoryById(id);

            viewModel.EnumCategoryID = id;
            viewModel.EnumCategoryCode = tblItem.Code;
            viewModel.EnumCategoryName = tblItem.Name;
            viewModel.EnumCategoryDesc = tblItem.Description;

            return View(viewModel);

        }
        [HttpPost]
        public ActionResult Edit(EnumVM viewModel)
        {
            try
            {
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {
                    if (ModelState.IsValid)
                    {

                        tbl_EnumCategory item = new tbl_EnumCategory()
                        {
                            ID = viewModel.EnumCategoryID,
                            Code = viewModel.EnumCategoryCode,
                            Name = viewModel.EnumCategoryName,
                            Description = viewModel.EnumCategoryDesc,
                            UpdateDate = DateTime.Now,
                            UpdateUser = UserProfile.UserId

                        };


                        CRUDOperation dataOperations = new CRUDOperation();
                        tbl_EnumCategory dbItem = dataOperations.UpdateEnumCategory(item);
                        if (dbItem != null)
                        {
                            TempData["success"] = "Ok";
                            TempData["message"] = "Məlumatlar uğurla dəyişdirildi";
                            return RedirectToAction("Index");

                        }
                        else
                        {
                            TempData["success"] = "notOk";
                            TempData["message"] = "Məlumatlar dəyişdirilərkən xəta baş verdi";
                            return RedirectToAction("Index");

                        }
                    }
                }

                throw new ApplicationException("Invalid model");
            }
            catch (ApplicationException ex)
            {

                return View(viewModel);
            }

        }
        [Description("Enum kategorini sil")]
        public ActionResult Delete(int id)
        {
            try
            {
                CRUDOperation dataOperations = new CRUDOperation();
                var UserProfile = (UserProfileSessionData)this.Session["UserProfile"];
                if (UserProfile != null)
                {
                    dataOperations.DeleteEnumCategory(id, UserProfile.UserId);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Error", "Error"));
            }
        }

    }
}

ScoreMe.UI/Views/EnumCategory/Create.cshtml
@model ScoreMe.UI.Models.EnumVM
@{
    ViewBag.Title = "Enum kategori əlavə edilməsi ekranı";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="row">

            <div class="col-md-4">
                @Html.LabelFor(model => model.EnumCategoryCode, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.EnumCategoryCode, new { htmlAttributes = new { @class = "form-control", tabindex = 1 } })
                @Html.ValidationMessageFor(model => model.EnumCategoryCode, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.EnumCategoryName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.EnumCategoryName, new { htmlAttributes = new { @class = "form-control", tabindex = 2 } })
                @Html.ValidationMessageFor(model => model.EnumCategoryName, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.EnumCategoryDesc, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.EnumCategoryDesc, new { htmlAttributes = new { @class = "form-control", tabindex = 3 } })
                @Html.ValidationMessageFor(model => model.EnumCategoryDesc, "", new { @class = "text-danger" })

            </div>    
       

        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-6 control-label">
                @Html.ActionLink("Listə Geri Dön", "Index", "EnumCategory", null, new { @class = "btn btn-primary btn-lg btn-block" })
            </div>
            <div class="col-md-6 control-label">
                <input id="frmPosition" type="submit" value="Yarat" class="btn btn-primary btn-lg btn-block" tabindex="9" />
            </div>
        </div>
    </div>
}

ScoreMe.UI/Views/EnumCategory/Edit.cshtml
@model ScoreMe.UI.Models.EnumVM
@{
    ViewBag.Title = "Enum kategori redakte edilməsi ekranı";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="row">

            <div class="col-md-4">
                @Html.HiddenFor(model => model.EnumCategoryID)
                @Html.LabelFor(model => model.EnumCategoryCode, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.EnumCategoryCode, new { htmlAttributes = new { @class = "form-control", tabindex = 1 } })
                @Html.ValidationMessageFor(model => model.EnumCategoryCode, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.EnumCategoryName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.EnumCategoryName, new { htmlAttributes = new { @class = "form-control", tabindex = 2 } })
                @Html.ValidationMessageFor(model => model.EnumCategoryName, "", new { @class = "text-danger" })

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.EnumCategoryDesc, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.EnumCategoryDesc, new { htmlAttributes = new { @class = "form-control", tabindex = 3 } })
                @Html.ValidationMessageFor(model => model.EnumCategoryDesc, "", new { @class = "text-danger" })

            </div>

        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-6 control-label">
                @Html.ActionLink("Listə Geri Dön", "Index", "EnumCategory", null, new { @class = "btn btn-primary btn-lg btn-block" })
            </div>
            <div class="col-md-6 control-label">
                <input id="frmPosition" type="submit" value="Dəyiş" class="btn btn-primary btn-lg btn-block" tabindex="9" />
            </div>
        </div>
    </div>
}

ScoreMe.UI/Views/EnumCategory/Index.cshtml
@model ScoreMe.UI.Models.EnumVM
@{
    ViewBag.Title = "Enum kategori siyahisi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-12">


        <div class="clearfix"></div><br />

        <div class="well bs-component">

            <a class="btn btn-warning pull-right btn-icon" href="@Url.Action("Create","EnumCategory")"><span class="fa fa-plus"></span> Əlavə et</a>

            <div class="clearfix"></div>
            <div class="table-responsive">
                <table class="table table-bordered" style="margin:0;">
                    <tbody>
                        <tr>
                            <th class="col-md-2" style="font-size:14px; text-align:center; vertical-align:middle; background-color: gainsboro;">
                                @Html.DisplayNameFor(model => model.EnumCategoryCode)
                                <input onkeyup="Search(this, 'EnumCategory', 'Index', 'Code')" class="form-control" placeholder="axtar" />
                            </th>
                            <th class="col-md-2" style="font-size:14px; text-align:center; vertical-align:middle; background-color: gainsboro;">
                                @Html.DisplayNameFor(model => model.EnumCategoryName)
                                <input onkeyup="Search(this, 'EnumCategory', 'Index', 'Name')" class="form-control" placeholder="axtar" />
                            </th>
                            <th class="col-md-2" style="font-size:14px; text-align:center; vertical-align:middle; background-color: gainsboro;">
                                @Html.DisplayNameFor(model => model.EnumCategoryDesc)
                            </th>
                      

                            <th class="col-md-1" style="font-size:14px; text-align:center; vertical-align:middle; background-color:gainsboro;">
                                Redaktə et
                                </br>
                                Sil
                            </th>
                        </tr>
                    </tbody>
                </table>
                <div id="AjaxPaginationList">
                    @Html.Partial("PartialIndex")
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/pagedList.js"></script>

ScoreMe.UI/Views/EnumCategory/PartialIndex.cshtml
@model ScoreMe.UI.Models.EnumVM
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "";
}




<div class="col-sm-1 col-sm-offset-11" style="position: absolute;">
    <span class="label label-danger pull-right badgemargin">@Model.ListCount</span>
</div>

<table class="table table-bordered">
    <tbody>
        @foreach (var item in Model.REnumCategoryList)
        {
            <tr>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => item.EnumCategoryCode)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => item.EnumCategoryName)
                </td>

                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => item.EnumCategoryDesc)
                </td>
            

                <td class="col-md-1 shsingle text-center" style="font-size:16px;">
                    <a class="btn btn-primary active  btn-xs" title="Redaktə et" href="@Url.Action("Edit","EnumCategory", new { id = item.EnumCategoryID})"><span class="fa fa-pencil"></span></a>
                    <span title="Sil"> @Html.ActionLink(" ", "Delete", "EnumCategory", new { id = item.EnumCategoryID }, new { @onclick = "return confirm('Silmək istədiyinizə əminsinizmi?.');", @class = "glyphicon glyphicon-trash" })</span>
                </td>

            </tr>
        }
    </tbody>
</table>


<div class="box-footer clearfix">
    Səhifə @(Model.Paging.PageCount < Model.Paging.PageNumber ? 0 : Model.Paging.PageNumber) (cəmi @Model.Paging.PageCount)
    @Html.PagedListPager(Model.Paging, page => Url.Action("Index", new { page }))
</div>